oc_plateform_home:
    path: /
    defaults: {_controller: OCPlatformBundle:Advert:index }

oc_platform_view:
    path: /advert/{id}
    defaults: {_controller:OCPlatformBundle:Advert:view }

oc_plateform_view_slug:
    path: /{year}/{slug}.{_format}
    defaults: 
        _controller: OCPlatformBundle:Advert:viewSlug 
        _format: html
    requirements:
        year: \d{4}
        _format: html|xml

oc_platform_add:
    path: /add
    defaults: {_controller: OCPlatformBundle:Advert:add }